name: aswespeakproject
favicon: null
layout_spectrum: 0.8570697100367397
typography_spectrum: 0.7425239426083863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9289672861341387
  lightness: 0.26433711126446724
  saturation: 0.08946423814631999
  rhythmicContrast: 0.07765002292580903
purpose: []
